function cur = act_inact_cur(a_param_act, a_param_inact, p, t)
  time_ones = ones(1, length(t));

  cur = ...
      f(a_param_act, t) .^ (p(:, 1) * time_ones) .* ...
      f(a_param_inact, t) .^ (p(:, 2) * time_ones) .* ...
      (p(:, 5) * time_ones) .* ...
      ((p(:, 4) - p(:, 3)) * time_ones);
end
