function cur_obj = param_I_t(param_init_val, a_param_act, a_param_inact, id, props)
  if ~ exist('props', 'var')
    props = struct;
  end

  cur_obj = ...
    param_func({'time [ms]', 'current [nA]'}, ...
               param_init_val, {'p', 'q', 'E', 'V', 'gmax'}, ...
               @(p, t) deal(act_inact_cur(a_param_act, a_param_inact, p, t), NaN), ...
               id, mergeStructs(props, struct('xMin', 0, 'xMax', 100)));
end
