%% Fit passive parameters and average traces from one cell using traceset_L1_passive

% data files not included
L1_K_datadir = [ './' ];

L1_Ca_datadir = ...
    [ L1_K_datadir 'Ca currents/WT_Ca/' ];

% browse
plotVclampAbf([ L1_Ca_datadir  ]);

% WT1
% cap: 15, 19
% act-inact: 16, 17, 18

wt_aCC1_Ca_actinact_vc1 = ...
    abf2voltage_clamp([ L1_Ca_datadir 'WT_aCC_1_Ca//11420019.abf' ]);

% use a traceset to load a set of files matching fileTempl and
% given file numbers
doc_dir_wt1 = 'Ca/VW-2011-04-L1/';
wt_aCC1_Ca_actinact_ts = ...
    traceset_L1_passive([15:19], ...
                        struct('passive', [15, 19], ...
                               'inactM90to40hold0', 16:18), ...
                        'WT_aCC_1_Ca_11420', ...
                        struct('fileTempl', '11420%03d.abf', ...
                               'baseDir', ...
                               [ L1_Ca_datadir 'WT_aCC_1_Ca/' ], ...
                               'docDir', doc_dir_wt1, ...
                               'timeAvg', 10));

% est passive params
[a_db, Cm_avg, plot_doc] = processCapEst(wt_aCC1_Ca_actinact_ts);


% average prots and save
[avg_vc sd_vc] = ...
    averageTracesSave(wt_aCC1_Ca_actinact_ts, 'inactM90to40hold0');


% plot I-V curve
plotFigure(plot_superpose({...
  plotSteadyIV(calcCurPeaks(avg_vc, 3, ...
                            struct('pulseStartRel', [2 2], ...
                                   'pulseEndRel', [2 36])), 3, '', ...
               struct('plotPeaks', 1, 'label', 'act peak (2-36 ms)', ...
                      'fixedSize', [5 2], 'noTitle', 1, ...
                      'axisProps', struct('Box', 'off'), ...
                      'legendLocation', 'EastOutside')), ...
  plotSteadyIV(avg_vc, 3, '', ...
               struct('stepRange', [2 2 36], 'label', 'act avg (2-36 ms)')), ...
  plotSteadyIV(calcCurPeaks(avg_vc, 3, ...
                            struct('pulseStartRel', [3 2], ...
                                   'pulseEndRel', [3 36])), 3, '', ...
               struct('plotPeaks', 1, 'label', 'inact peak (2-36 ms)')), ...
  plotSteadyIV(avg_vc, 3, '', ...
               struct('stepRange', [2 80 100], 'label', 'steady avg (80-100 ms)'))}, {}, ''));

%% Average across cells using cellset_L1

doc_dir = 'Ca/VW-2011-04-L1';

% for each cell do:
Ca1_ts = ...
    traceset_L1_passive([15:19], ...
                        struct('passive', [15:19], ...
                               'holdM90Ca', [16:18]), ...
                        'Ca_1', ...
                        struct('fileTempl', '11420%03d.abf', ...
                               'baseDir', ...
                               [ L1_K_datadir 'Ca currents/WT_Ca/WT_aCC_1_Ca/' ], ...
                               'docDir', doc_dir, ...
                               'timeAvg', 10));
Ca2_ts = ...
    traceset_L1_passive([21:25], ...
                        struct('passive', [21:25], ...
                               'holdM90Ca', [22:24]), ...
                        'Ca_2', ...
                        struct('fileTempl', '11420%03d.abf', ...
                               'baseDir', ...
                               [ L1_K_datadir 'Ca currents/WT_Ca/WT_aCC_2_Ca/' ], ...
                               'docDir', doc_dir, ...
                               'timeAvg', 10));
                           
Ca3_ts = ...
    traceset_L1_passive([31:35], ...
                        struct('passive', [31:35], ...
                               'holdM90Ca', [32:34]), ...
                       'Ca_3', ...
                        struct('fileTempl', '11420%03d.abf', ...
                               'baseDir', ...
                               [ L1_K_datadir 'Ca currents/WT_Ca/WT_aCC_3_Ca/' ], ...
                               'docDir', doc_dir, ...
                               'timeAvg', 10));
Ca4_ts = ...
    traceset_L1_passive([47:51], ...
                        struct('passive', [47:51], ...
                               'holdM90Ca', [48:50]), ...
                        'Ca_4', ...
                        struct('fileTempl', '11420%03d.abf', ...
                               'baseDir', ...
                               [ L1_K_datadir 'Ca currents/WT_Ca/WT_aCC_4_Ca/' ], ...
                               'docDir', doc_dir, ...
                               'timeAvg', 10));
Ca5_ts = ...
    traceset_L1_passive([57:61], ...
                        struct('passive', [57:61], ...
                               'holdM90Ca', [58:60]), ...
                        'Ca_5', ...
                        struct('fileTempl', '11420%03d.abf', ...
                               'baseDir', ...
                               [ L1_K_datadir 'Ca currents/WT_Ca/WT_aCC_5_Ca/' ], ...
                               'docDir', doc_dir, ...
                               'timeAvg', 10));

% all cells
zoomparams = struct('holdM90Ca', [120 180 -8e-8 6e-8]);
prots = struct;
prots.averageTracesSave = {...
  'holdM90Ca'};
Ca_cells = ...
    cellset_L1({Ca2_ts, Ca3_ts, Ca4_ts, Ca5_ts}, prots, ...
               ['Ca currents recorded on 2011/4/20'], ...
               struct('docDir', doc_dir, 'protZoom', ...
                      zoomparams));
                  
% cap est across cells
[a_db, a_stats_db, Cm_avg_db] = ...
    processCapEst(Ca_cells, struct('closeFigs', 1));

% averaging across cells
prot_props = struct;
[tex_file] = averageTracesSave(Ca_cells); 
